<a href="https://colab.research.google.com/github/ActiveStacks/AI_with_PyTorch/blob/main/Pytorchai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy
import numpy as np

In [ ]:
my_list  = [[1,2,3,4], [3,5,6,7]]
my_list

[[1, 2, 3, 4], [3, 5, 6, 7]]

In [ ]:
np1 = np.random.rand(3,4)
np1

In [ ]:
tensor_2d = torch.rand(3,4)
tensor_2d


tensor([[0.1175, 0.9804, 0.0962, 0.4956],
        [0.8923, 0.8430, 0.6709, 0.0476],
        [0.0358, 0.9061, 0.8120, 0.2086]])

In [ ]:
tensor_3d = torch.rand(3,4,5)
tensor_3d

tensor([[[0.4058, 0.4324, 0.9403, 0.2014, 0.6881],
         [0.1586, 0.0386, 0.4665, 0.7912, 0.6828],
         [0.1593, 0.9836, 0.4077, 0.5394, 0.2892],
         [0.0489, 0.7342, 0.2108, 0.2649, 0.6376]],

        [[0.7936, 0.8920, 0.7970, 0.9036, 0.5114],
         [0.9554, 0.0541, 0.9984, 0.2211, 0.5966],
         [0.9696, 0.1497, 0.9782, 0.2970, 0.3547],
         [0.7867, 0.7112, 0.2844, 0.6100, 0.3353]],

        [[0.4595, 0.8376, 0.4018, 0.7540, 0.6860],
         [0.6197, 0.1261, 0.4887, 0.4165, 0.7180],
         [0.9748, 0.8966, 0.0542, 0.5289, 0.6522],
         [0.6977, 0.7569, 0.9857, 0.5677, 0.2025]]])

In [ ]:
# CREATE TENSOR FROM NUMP ARRAY
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.7933, 0.3434, 0.6596, 0.4793],
        [0.7069, 0.7196, 0.8145, 0.5437],
        [0.0035, 0.1331, 0.3753, 0.2578]], dtype=torch.float64)