<a href="https://colab.research.google.com/github/ActiveStacks/AI_with_PyTorch/blob/main/Pytorchmaths.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy
import numpy as np

In [ ]:
my_list  = [[1,2,3,4], [3,5,6,7]]
my_list

[[1, 2, 3, 4], [3, 5, 6, 7]]

In [ ]:
np1 = np.random.rand(3,4)
np1

In [ ]:
tensor_2d = torch.rand(3,4)
tensor_2d


tensor([[0.1175, 0.9804, 0.0962, 0.4956],
        [0.8923, 0.8430, 0.6709, 0.0476],
        [0.0358, 0.9061, 0.8120, 0.2086]])

In [ ]:
tensor_3d = torch.rand(3,4,5)
tensor_3d

tensor([[[0.4058, 0.4324, 0.9403, 0.2014, 0.6881],
         [0.1586, 0.0386, 0.4665, 0.7912, 0.6828],
         [0.1593, 0.9836, 0.4077, 0.5394, 0.2892],
         [0.0489, 0.7342, 0.2108, 0.2649, 0.6376]],

        [[0.7936, 0.8920, 0.7970, 0.9036, 0.5114],
         [0.9554, 0.0541, 0.9984, 0.2211, 0.5966],
         [0.9696, 0.1497, 0.9782, 0.2970, 0.3547],
         [0.7867, 0.7112, 0.2844, 0.6100, 0.3353]],

        [[0.4595, 0.8376, 0.4018, 0.7540, 0.6860],
         [0.6197, 0.1261, 0.4887, 0.4165, 0.7180],
         [0.9748, 0.8966, 0.0542, 0.5289, 0.6522],
         [0.6977, 0.7569, 0.9857, 0.5677, 0.2025]]])

In [ ]:
# CREATE TENSOR FROM NUMP ARRAY
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.7933, 0.3434, 0.6596, 0.4793],
        [0.7069, 0.7196, 0.8145, 0.5437],
        [0.0035, 0.1331, 0.3753, 0.2578]], dtype=torch.float64)

In [9]:

my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
my_torch = my_torch.reshape(5,2)
my_torch

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [17]:
my_torch2 = my_torch.reshape(-1,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [20]:
my_torch4 = my_torch2.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [21]:
# SLCIES
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
my_torch7[7]

tensor(7)

In [23]:
# GRAB SLICE
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [24]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [25]:
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

In [27]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [28]:
# ADDITION
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [29]:
# ADDITION LONGHAND
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [30]:
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [31]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [32]:
torch.sub(tensor_a, tensor_b)

tensor([-4, -4, -4, -4])

In [33]:
# MULTIP,ICATION
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [34]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [35]:
# DIVISION
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [36]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [37]:
# MODULUS
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [40]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [41]:
# EXPONENTS
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [42]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [ ]:
torch.add_(tensor_a, tensor_b)

In [45]:
tensor_a = tensor_a + tensor_b
tensor_a

tensor([16, 20, 24, 28])